// src/components/shared/Toolbar.tsx
import { useNavigate, useRouteLoaderData } from 'react-router';
import { ArrowLeftIcon } from '@heroicons/react/24/outline';
import Logo from './Logo';

function Toolbar() {
  const navigate = useNavigate();
  const isCharacterPage = useRouteLoaderData('character'); // This will only be true on /character route due to loader in router config

  const handleClick = () => navigate('/');

  return (
    <div className='w-full py-4 bg-white'>
      <div className='flex content-center items-center space-x-4 px-4'>
        {isCharacterPage && (
          <span
            className='h-10 cursor-pointer grid place-content-center pr-4 border-r-2 border-gray-200 group'
            onClick={handleClick}
          >
            <ArrowLeftIcon className='fill-current w-4 h-4 text-gray-300 transition ease-in-out duration-300 group-hover:text-green-600' />
          </span>
        )}
        <Logo />
      </div>
    </div>
  );
}

export default Toolbar;

// src/components/shared/Toolbar.vue
<template>
  <div class="toolbar">
    <div class="tb--container">
      <span v-if="route.name === 'character'" class="back-btn group" @click="router.push({ name: 'home' })">
        <ArrowLeftIcon class="icon group-hover:text-green-600" />
      </span>
      <Logo />
    </div>
  </div>
</template>

<script setup>
import { useRouter, useRoute } from 'vue-router';
import { ArrowLeftIcon } from '@heroicons/vue/outline';

const route = useRoute();
const router = useRouter();
</script>

<style scoped>
.toolbar {
  @apply w-full py-4 bg-white mb-12;
}
.tb--container {
  @apply flex content-center items-center space-x-4 px-4;
}
.back-btn {
  @apply h-10 cursor-pointer grid place-content-center pr-4 border-r-2 border-gray-200;
}
.icon {
  @apply fill-current w-4 h-4 text-gray-300 transition ease-in-out duration-300;
}
</style>
