// src/components/Character.vue
<template>
  <div class="container mx-auto px-4">
    <div class="flex flex-col md:flex-row bg-white rounded-xl overflow-hidden space-x-8">
      <img :src="store.currentCharacter.image" :alt="store.currentCharacter.name" class="w-full md:w-1/2" />
      <section class="flex flex-col items-start py-4 space-y-4">
        <h1 class="text-4xl mb-4 uppercase font-black tracking-widest">{{ store.currentCharacter.name }}</h1>
        <Pill :status="'species'">
          {{ store.currentCharacter.species + ' - ' + store.currentCharacter.gender }}
        </Pill>
        <Pill :status="store.currentCharacter.status?.toLowerCase()">
          {{ store.currentCharacter.status }}
        </Pill>
        <span class="flex justify-center">
          <LocationMarkerIcon class="h-6 w-6 mr-2 stroke-current text-gray-300" />
          Location: {{ store.currentCharacter.location?.name }}</span
        >
        <span class="flex justify-center">
          <HomeIcon class="h-6 w-6 mr-2 stroke-current text-gray-300" />
          Origin: {{ store.currentCharacter.origin?.name }}</span
        >
      </section>
    </div>
  </div>
</template>

<script setup>
import { onUnmounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useStore } from '@/store';
import { LocationMarkerIcon, HomeIcon } from '@heroicons/vue/outline';

const route = useRoute();
const router = useRouter();
const store = useStore();

if (/[0-9]+/.test(route.params.id)) {
  store.fetchCurrentCharacter(route.params.id);
} else {
  router.push({ name: 'NotFound' });
}

onUnmounted(() => store.resetCurrentCharacter());
</script>

<style scoped></style>

// src/components/Character.tsx
import { MapPinIcon, HomeIcon } from '@heroicons/react/24/outline';
import StatusPill from './shared/StatusPill';
import useStore from '@/store';

const Character = () => {
  const currentCharacter = useStore(state => state.currentCharacter);

  return (
    <div className='container mx-auto py-8 px-4'>
      <div className='flex flex-col md:flex-row bg-white rounded-xl overflow-hidden space-x-8'>
        <img src={currentCharacter.image} alt={currentCharacter.name} className='w-full md:w-1/2' />
        <section className='flex flex-col items-start py-4 space-y-4'>
          <h1 className='text-4xl mb-4 uppercase font-black tracking-widest'>{currentCharacter.name}</h1>
          <StatusPill status='species'>{currentCharacter.species + ' - ' + currentCharacter.gender}</StatusPill>
          <StatusPill status={currentCharacter.status?.toLowerCase()}>{currentCharacter.status}</StatusPill>
          <span className='flex justify-center'>
            <MapPinIcon className='h-6 w-6 mr-2 stroke-current text-gray-300' />
            Location: {currentCharacter.location?.name}
          </span>
          <span className='flex justify-center'>
            <HomeIcon className='h-6 w-6 mr-2 stroke-current text-gray-300' />
            Origin: {currentCharacter.origin?.name}
          </span>
        </section>
      </div>
    </div>
  );
};

export default Character;
