// src/components/Characters.tsx
import useStore from '@/store';
import Card from './shared/Card';
import type { Character } from '@/types';
import SearchBar from './shared/SearchBar';

const Characters = () => {
  const characters = useStore(state => state.characters);
  const cards = characters.map((c: Character) => <Card key={c.id} id={c.id} img={c.image} name={c.name} />);
  return (
    <div className='container mx-auto py-8 px-4 md:px-0'>
      <SearchBar />
      <section className='characters--grid grid grid-cols-1 md:grid-cols-5 gap-4'>{cards}</section>
    </div>
  );
};

export default Characters;

// src/components/Characters.vue
<template>
  <div class="container mx-auto px-4 md:px-0">
    <Searchbar />
    <section v-if="characters.length" class="characters--grid grid grid-cols-1 md:grid-cols-5 gap-4">
      <Card v-for="character in characters"
            :id="character.id"
            :img="character.image"
            :name="character.name"
            />
    </section>
    <NoResults v-else />
    <Pagination />
  </div>
</template>

<script setup>
import { storeToRefs } from 'pinia';
import Searchbar from "./shared/Searchbar.vue";
import Card from './shared/Card.vue';
import Pagination from "./shared/Pagination.vue";
import NoResults from "./shared/NoResults.vue";
import { useStore } from '@/store';

const store = useStore();
const { characters } = storeToRefs(store);

store.fetchCharacters();
</script>

<style scoped>

</style>
